# window
hide_window_decorations titlebar-only
window_padding_width 10 5

# font
font_family      family="JetBrainsMono Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto

# color scheme
include vague.conf

# tab bar
tab_bar_min_tabs 2
tab_bar_style fade
tab_fade 1
tab_title_max_length 20
tab_title_template "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{tab.last_focused_progress_percent}{index}: {title}"

# os specific config
include kitty.${KITTY_OS}.conf
