font_family      family='JetBrainsMono Nerd Font Mono' postscript_name=JetBrainsMonoNFM-Regular
bold_font        family='JetBrainsMono Nerd Font Mono' style=Bold
italic_font      auto
bold_italic_font family='JetBrainsMono Nerd Font Mono' style='Bold Italic'

font_size 13.0

modify_font cell_height 112%
modify_font cell_width 96%

window_padding_width 15

include vague.conf

hide_window_decorations titlebar-only

map ctrl+j neighboring_window down
map ctrl+k neighboring_window up
map ctrl+h neighboring_window left
map ctrl+l neighboring_window right

map --when-focus-on var:IS_NVIM ctrl+j
map --when-focus-on var:IS_NVIM ctrl+k
map --when-focus-on var:IS_NVIM ctrl+h
map --when-focus-on var:IS_NVIM ctrl+l

map ctrl+down  kitten relative_resize.py down  5
map ctrl+up    kitten relative_resize.py up    5
map ctrl+left  kitten relative_resize.py left  5
map ctrl+right kitten relative_resize.py right 5

map --when-focus-on var:IS_NVIM ctrl+down
map --when-focus-on var:IS_NVIM ctrl+up
map --when-focus-on var:IS_NVIM ctrl+left
map --when-focus-on var:IS_NVIM ctrl+right
