[flavor]
dark = "modus-vivendi-soft"
light = "modus-operandi-soft"

[status]
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }

[indicator]
padding = { open = "█", close = "█" }
