#!/usr/bin/env bash

options=(
  style=round
  active_color="gradient(top_left=0xeecdcdcd,bottom_right=0xee878787)"
  inactive_color=0x00cdcdcd
  width=4.0
  hidpi=on
  order=above
)

borders "${options[@]}"
