[app]
overall = { bg = "#151515" }

[mgr]
cwd = { fg = "#8fbfdc", italic = true }
hovered = { fg = "#e8e8d3", bg = "#1c1c1c" }
preview_hovered = { bg = "#1c1c1c" }
marker_copied = { fg = "#99ad6a", bg = "#99ad6a" }
marker_cut = { fg = "#cf6a4c", bg = "#cf6a4c" }
marker_marked = { fg = "#c6b6ee", bg = "#c6b6ee" }
marker_selected = { fg = "#fad07a", bg = "#fad07a" }
border_style = { fg = "#404040" }

[tabs]
active = { fg = "#151515", bg = "#8fbfdc", bold = true }
inactive = { fg = "#888888", bg = "#1c1c1c" }

[mode]
normal_main = { fg = "#151515", bg = "#8fbfdc", bold = true }
normal_alt = { fg = "#e8e8d3", bg = "#404040" }
select_main = { fg = "#151515", bg = "#c6b6ee", bold = true }
select_alt = { fg = "#e8e8d3", bg = "#404040" }
unset_main = { fg = "#e8e8d3", bg = "#700089", bold = true }
unset_alt = { fg = "#e8e8d3", bg = "#404040" }
