name: <%= ENV["DEV_REPO_NAME"] %>
root: <%= ENV["DEV_REPO_ROOT"] %>

windows:
  - editor:
      layout: main-vertical-mirrored
      panes:
        - claude
        - nvim
        -
  - server:
      layout: even-horizontal
      panes:
        -
        -
